### ISSUE TITLE
Add link to Quick Start Guide in info.html

### ISSUE THREAD

**Issue by jamesmaa** [yomidevs/yomitan#1508]
Between the "Yomitan" header and General section, create a new section that asks if the user needs help, and link a button that navigates them to the Quick Start Guide.

<img width="726" alt="image" src="https://github.com/user-attachments/assets/28b225b6-f178-488b-abf0-7cb021e8afbe">

I'm guessing users will click on the Info button because it looks like a help icon.
<img width="108" alt="image" src="https://github.com/user-attachments/assets/885a35f9-b77e-41fb-9db3-c420f167b378">

**Comment by tomodutch** [comment]
GrumpyThomas here, I would like to pick this one up. Any ideas what text we want to show to the user?

**Comment by jamesmaa** [comment]
Maybe something like "New to Yomitan? Check out the Quick Start Guide Here"? It does feel weird to have a title outside of the box 🤔 I wonder if we can add two line items, one for the quick start guide and the other for the yomitan.wiki site

**Comment by tomodutch** [comment]
A) Without header
![image](https://github.com/user-attachments/assets/621292e7-f631-477e-9bfe-adabee9aee1c)

B) With header (consistent with other pages)
![image](https://github.com/user-attachments/assets/dc8f99a4-9195-4e63-9f05-ce72cddfe221)

The wiki button links to https://yomitan.wiki/getting-started/#basic-usage as I figured the user may want to skip the information about installation as the extension is already installed.

I do have two small concerns about the user experience:

1) by adding the wiki as a link there are now 2 getting started guides...
2) Very nitpicky but the quick start guide has a button on the bottom that links back to the welcome page instead of the info page where the user came from. 
![image](https://github.com/user-attachments/assets/79b608c4-7c74-4c37-a2f3-57fbafb4765d)

**Comment by jamesmaa** [comment]
Let's do with header and change the header to "Need help?"
Line item 1: "Check out the Quick Start Guide"
Line item 2: "Read the wiki for more information"

> I do have two small concerns about the user experience:

1. Maybe we can just link to the homepage? Line item 1 could be for beginners looking to start and line item 2 could be for more exploration.
2. Oh yeah hmm maybe we can just remove it or have it go back? I never noticed it haha

**Comment by tomodutch** [comment]
Made a PR #1510. Let me know what you think :)
