### ISSUE TITLE
Annotate "Japanese Only" in "Pitch accent display styles" setting

### ISSUE THREAD

**Issue by jamesmaa** [yomidevs/yomitan#1612]
<img width="668" alt="image" src="https://github.com/user-attachments/assets/a3c91de0-108d-4f69-a443-301c74ebd6ff">

Maybe audit through other settings for japanese only settings

**Comment by impucky** [comment]
Hello! 
I'm interested in contributing to Yomitan and this seems simple enough to dip my toes.

Is this okay?
![chrome_FxI9h2k3VF](https://github.com/user-attachments/assets/4e90431f-cc11-4650-a0ea-b0bc739ca7e6)
![chrome_TDjKFJcfVa](https://github.com/user-attachments/assets/fb98b7af-b29d-42c5-9dd2-dc9dea3b611f)

The other Japanese specific settings I could find are:
- **Term display style**
- **Reading mode**

Maybe those could use a similar annotation? Since all three (including Pitch accent styles) are under Appearance maybe they can at least be grouped together.
<br />
- **Search text with non-Japanese, Chinese, or Cantonese characters** (Scanning)
- **Enable background clipboard text monitoring** (Clipboard)

Those could maybe be generalized to something like "any non-latin script that matches the currently enabled language"?
But that's beyond the scope of this issue.
<br />
- **Parse sentences using MeCab** (Text Parsing)

Afaik this is also Japanese only, could maybe use an annotation too.
<br />
I can probably also pick up #1609 and #1610

**Comment by jamesmaa** [comment]
Thanks for auditing the settings! 

Yeah the annotation seems good. Maybe "Japanese only" to make it shorter? 

For `Term display style" I wouldn't touch it. It looks like we use it for Chinese as well (even though it's not labeled correctly). `Reading mode` doesn't seem to do anything for Chinese so I think it's fine to label?

> Maybe those could use a similar annotation? Since all three (including Pitch accent styles) are under Appearance maybe they can at least be grouped together.

Might be a good idea! We can consider creating a new issue to capture that rather than expand the scope of that instead of adding onto this.

> Those could maybe be generalized to something like "any non-latin script that matches the currently enabled language"?

Let's discuss this in a new issue. Feel free to file it.

> Parse sentences using MeCab (Text Parsing)

Yeah I think we could add an annotation here too.

Separately, #1609 and #1610 are very doable and more straightforward. 

If you're looking to contribute more deeply could you review this PR? https://github.com/yomidevs/yomitan/pull/1626

**Comment by Kuuuube** [comment]
Could also add the css class to hide it when languages other than japanese are selected.

**Comment by impucky** [comment]
It looks like the class is only used for Scan resolution currently.
I could add it to the Pitch display, Reading mode and MeCab settings on top of the annotations?

**Comment by StefanVukovic99** [comment]
`Pitch display` might still have some effect on IPA display, see #1042.

**Comment by Kuuuube** [comment]
It shouldnt anymore (#1306).

**Comment by Kuuuube** [comment]
I dont think zh and yue need to see those settings. You can make another css class for only jp if one doesnt exist. It should be obvious how to set that up just reference the existing ones in the css.

**Comment by impucky** [comment]
Ok I can add that class. Though since you mentioned in #1306 that other languages use pitch dictionaries, now I'm confused if the setting needs an annotation in the first place?

**Comment by Kuuuube** [comment]
I forget exactly where i saw the usage in other languages. Would be good if we can get comment from other language users on this. If you want to go ahead and push things along it can be excluded for now.
