### ISSUE TITLE
All my dictionaries are deleted for no reason???

### ISSUE THREAD

**Issue by phamthaison1207** [yomidevs/yomitan#1629]
**Description**
(Describe what the issue is, if it is reproducible, and if possible, how to reproduce it.)
I don't know if it's reproducible or not, all my dictionaries are wiped on this new version
**Browser version**
Chromium
Version 122.0.6261.115 (Official Build, ungoogled-chromium) (64-bit)
**Yomitan version**
 Yomitan 24.11.23.0

**Exported settings file**
[yomitan-settings-2024-11-30-16-40-18.json](https://github.com/user-attachments/files/17966117/yomitan-settings-2024-11-30-16-40-18.json)
![image](https://github.com/user-attachments/assets/15ebd593-1ac9-4c2b-a73c-3778e9fbb02e)

**Comment by Kuuuube** [comment]
Unfortunately, in some rare cases, browsers will decide to bulldoze all of your data. I'm not sure if this is a browser bug or intentional but it can happen to any extension. Data is also deleted if you reinstall the extension rather than updating it.

This is not a Yomitan issue and there is nothing we can do about this. Theres no "bad update" from Yomitan. You either have some messed up browser settings, found a bug in your browser, or just got unlucky.

**Comment by phamthaison1207** [comment]
thank you Kuuube =((
